# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d14e17ffad3b55a31b727379854540df46c4665b3c464b8d9b0272a98af08c88ae27e7341c6c732173561f39d01629133d0b041f11e503a6e44b5d3731a259d9

test:
  secret_key_base: 64d6dd9ccdcc02bf287a545126c7492500d1c44a5043391e8717930e97d70fce142befadc23a03c0da2003801d6b789f7a78b939e0ef318c2cf09b1d0a564383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
